Repository HungerStation/hs_protos, pull requests merged in 2021-02, with the labels that each got.

#5 feat: add email notifications
  notification/email/email.pb.go
  notification/email/email.proto
  notification/email/email_pb.rb
Labels: size/XL

#6 feat: add service token to protofiles
  notification/email/email.pb.go
  notification/email/email.proto
  notification/email/email_pb.rb
  notification/push/android/android.pb.go
  notification/push/android/android.proto
  notification/push/android/android_pb.rb
  notification/push/ios/ios.pb.go
  notification/push/ios/ios.proto
  notification/push/ios/ios_pb.rb
  notification/slack/slack.proto
  notification/sms/sms.pb.go
  notification/sms/sms.proto
  notification/sms/sms_pb.rb
Labels: size/XL

#7 feat: generate proto for slack
  notification/slack/slack.pb.go
  notification/slack/slack_pb.rb
Labels: size/L

#8 Feature/hbp 325 add source
  notification/email/email.pb.go
  notification/email/email.proto
  notification/email/email_pb.rb
Labels: size/M
